### PR TITLE
Remove empty JavaFX jars from modulepath

### LINKED ISSUE #101: Remove empty JavaFX jars from modulepath
JavaFX Gradle plugin leaves JavaFX empty(non-platform)  jars on modulepath.

With the change made in [JDK-8264998](https://bugs.openjdk.java.net/browse/JDK-8264998), keeping empty jars on the modulepath can result in the following exception:

```
> Task :run FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for ~/.m2/repository/org/openjfx/javafx-controls/17-ea+8/javafx-controls-17-ea+8.jar
Caused by: java.lang.IllegalArgumentException: javafx.controls.17.ea.8: Invalid module name: '17' is not a Java identifier
```

Some explanation on what's going on:

1. If a jar is on Module path and it doesn't has a Automatic-Module-Name, then Java tries to create a module name from the jar
2. This is done by bisecting the jar name and a number in between text can cause issues: https://docs.oracle.com/javase/9/docs/api/java/lang/module/ModuleFinder.html#automatic-modules
3. Therefore, an empty jar for version "17" may work fine with empty jars containing no module-name. However, empty jars for version `17-ea+8` will fail since a number between alphabets is not supported.

In order to adapt the change made in [JDK-8264998](https://bugs.openjdk.java.net/browse/JDK-8264998), empty jars should be removed from the modulepath.

### PR DESCRIPTION
**Pull request by abhinayagarwal**
Fixes #101

### CODE REVIEW

File: src/main/java/org/openjfx/gradle/tasks/ExecTask.java [hunk 1]
```diff
@@ -74,13 +79,21 @@ public void action() {
             var definedJavaFXModuleNames = new TreeSet<>(javaFXOptions.getModules());
             if (!definedJavaFXModuleNames.isEmpty()) {
                 RunModuleOptions moduleOptions = execTask.getExtensions().findByType(RunModuleOptions.class);
+
+                // BEGIN: Remove JavaFX empty jars from classpath
+                final FileCollection classpathWithoutJavaFXJars = execTask.getClasspath().filter(
+                        jar -> Arrays.stream(JavaFXModule.values()).noneMatch(javaFXModule -> jar.getName().contains(javaFXModule.getArtifactName()))
+                );
+                final FileCollection javaFXCPWithoutEmptyJars = execTask.getClasspath().filter(jar -> isJavaFXJar(jar, javaFXOptions.getPlatform()));
```
Comment (johanvos) [inline src/main/java/org/openjfx/gradle/tasks/ExecTask.java:87]: iiuc, you're not removing the empty jars, but you are only considering the jars for the given Platform? 
That probably comes down to the same though, so I agree with that approach, just want to check if that is indeed what is happening?

Comment (abhinayagarwal) [reply src/main/java/org/openjfx/gradle/tasks/ExecTask.java:87]: As you said, it comes down to the same thing. Currently, the plugin adds both empty and platform specific JavaFX jars to the list of dependencies in the classpath. This PR tends to change the behaviour by *removing* the empty JavaFX jars from the list.

**Review by johanvos — APPROVED** [review]

**Review by jperedadnr — APPROVED** [review]
