### PR TITLE
Version less comparision for JavaFX modules on classpath

### LINKED ISSUE #69: Project with transitive dependency on newer version of JavaFX fails
Consider a scenario where a project with `javafx-gradle-plugin` is trying to use version 11 for JavaFX modules and it also has a dependency on ControlsFX 11.0.2.

```
javafx {
    version = "11"
    modules = [ 'javafx.controls' ]
}

dependencies {
      compile 'org.controlsfx:controlsfx:11.0.1'
}
```

In this case the project will fail to run. ControlsFX introduces a transitive dependency to JavaFX 11.0.2 and since classpath always uses the latest version, the plugin fails to find JavaFX modules with version 11 on the classpath.

This can be fixed by doing a version-less comparison while adding JavaFX modules to module-path from the classpath.

### PR DESCRIPTION
**Pull request by abhinayagarwal**
This PR is an attempt to fix transitive dependency failure. It happens when a transitive dependency is introduced in the project which uses a higher JavaFX module version than the one defined in `javafx { }`. For more details and an example of the issue, check #69.

Fixes #69

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
The tests fail because I have introduced a new smoke test case which depends on this fix :)

**Comment by tiainen** [comment]
@abhinayagarwal the tests are running on this PR. If you introduced a new test, it should not fail, unless I am missing something.

File: src/main/java/org/openjfx/gradle/JavaFXModule.java [hunk 1]
```diff
@@ -76,8 +76,15 @@ public String getArtifactName() {
         return PREFIX_ARTIFACT + name().toLowerCase(Locale.ROOT);
     }
 
-    public String getPlatformJarFileName(String version, JavaFXPlatform platform) {
-        return getArtifactName() + "-" + version + "-" + platform.getClassifier() + ".jar";
+    public boolean compareToJarFile(JavaFXPlatform platform, String jarFileName) {
```
Comment (tiainen) [inline src/main/java/org/openjfx/gradle/JavaFXModule.java]: This can be simplified by matching it with a regex?

    Pattern p = Pattern.compile(getArtifactName() + "-.+-" + platform.getClassifier() + "\\.jar";
    return p.matcher(jarFileName).matches();

**Comment by abhinayagarwal** [comment]
@tiainen The smoke tests use a [particular version of the plugin](https://github.com/openjfx/javafx-gradle-plugin/blob/master/test-project/build.gradle#L8).

**Comment by tiainen** [comment]
Ok, it still feels strange to add a test that fails. We can:

1. remove the test
2. remove the test and add it in a follow-up PR
3. fix the test, e.g. by letting the test-project depend on a locally installed version of the project

**Comment by abhinayagarwal** [comment]
I am not sure if '3' is possible. We can try to do '2'.
